project-everest/everparse

src/rfc_fstar_compiler.ml
tests/unittests.rfc

When constructed types require internal parser definitions, write them to separate modules (with interfaces). This should improve verification for complex types with many inline definitions.

Interfaces for all parsers

---

.gitignore
c3d/src/C3d.cpp
c3d/src/Makefile
c3d/tests/basic0.h
c3d/tests/basic1.h
c3d/tests/basic2.h
src/3d/ocaml/.gitignore

Hi @msprotz, mostly posting this for review. I added support for where clauses mostly mimicking your existing code for parameters. The tricky bit was adding `this` into the parsing context, which I think came out OK (details in commit messages + comments). I haven't yet refactored anything, wanted to check whether the logic seems OK.
For constraints and their scope, I was thinking we could do a similar trick for the scoping: push a new scope before parsing the constraint, push all the previously-parsed fields, and then parse the constraint. That would make the scopes clean, and seems implementable, but would be quadratic--- are we expecting big (~100 field) structures? Ideally we would carry the "ghost" scope while parsing, but seems like that would require clang surgery.
As an example, …

C3d: Where clauses

---

c3d/src/C3d.cpp

See comments. Figured out how to use the Rewrite API to strategically insert comments to disable attribute blocks in the preprocessed header. This solves a bunch of issues in #30, there's of course some things to polish but that should be enough for now.

Make the RewriteBuf work... location computations still approximate, that'll do for now

---

c3d/src/C3d.cpp
c3d/tests/basic0.h
c3d/tests/case.h

Here's a first implementation of enums and unions in C3d. Basic idea is:
1- `enum`s with an `everparse::process` attribute get translated, there are no other knobs for them. The 3d source gets all initializers fully spelled out, but that can be disabled (I left an `if (true)` in the source).
2- C unions marked with a `process` **must** have a **single** `everparse::switch` attribute which has a declaration argument (i.e. type + var name). Then, the cases **must** have an `everparse::case` attribute, which has an expression argument representing the label of the casetype branching.
This is based over your RewriteBuf PR and over my scoping PR too. Those two already look good to me,

C3d: supporting unions and enums

---

c3d/src/C3d.cpp
c3d/tests/basic0.h

Hi @msprotz, here's a first attempt at fixing the scoping, but with some issues. Here's the commit message:
--------
The vector just keeps information to create a VarDecl at the time when
we wish to enter the C3d scope. For now, we ony use it in C3dParseExpr
which pushes the C3d scope, parses an expression, and pops the scope.
This fixes the leakage of parameters and field names into the rest of
the program.
Further, note that was actually dangerous since resolution of `sizeof`
happens at this stage. Previously, this struct:
typedef struct
[[
everparse::entrypoint,
everparse::process,
everparse::parameter(uint32_t len)
]]
_FOO {
int arr[sizeof len];
} FOO;
Was actually outputting:
typedef struct
[[
everparse::entrypoint,
everparse::process,
everparse::parameter(uint32_t len)
]]
_FOO {
int …

RFC: C3d: rework scoping via an internal static vector of variables

---

src/lowparse/LowParse.Low.BitSum.fst
src/lowparse/LowParse.Spec.BitSum.fst

This PR prepares for the merge of F* PR https://github.com/FStarLang/FStar/pull/2205 into F* master.
It removes uses of FStar.WellFounded in LowParse.*.BitSum

Removing uses for FStar.WellFounded in BitSum

---

src/3d/Deps.fst
src/3d/OS.fsti
src/3d/ocaml/OS.ml

Given 
```
typedef A.t At
```
where A is unbound, this now fails with
```
.\Constants.3d:(15,9): (Error) Dependency not found: A
```

Nik check dep exists

---

.docker/build/config.json
src/3d/ocaml/Batch.ml

This would prevent any race conditions in trying to compile WeakenTac in multiple threads. If the cmxs is not found, we will fail hard.

Use --load_cmxs option for loading WeakenTac in F* invocations from 3d

---

src/3d/Target.fst

Definitions that are marked export should not be tagged as CInline, since at least MSVC treats this as also static and local to a compilation unit

Nik noinline export

---

doc/3d-snapshot/BoundedSum.c
doc/3d-snapshot/BoundedSumConst.c
doc/3d-snapshot/BoundedSumConstWrapper.c
doc/3d-snapshot/BoundedSumWhere.c
doc/3d-snapshot/BoundedSumWhereWrapper.c
doc/3d-snapshot/BoundedSumWrapper.c
doc/3d-snapshot/Color.c
doc/3d-snapshot/ColorWrapper.c
doc/3d-snapshot/ColoredPoint.c
doc/3d-snapshot/GetFieldPtr.c
doc/3d-snapshot/GetFieldPtrWrapper.c
doc/3d-snapshot/HelloWorld.c
doc/3d-snapshot/HelloWorldWrapper.c
doc/3d-snapshot/OrderedPair.c
doc/3d-snapshot/OrderedPairWrapper.c
doc/3d-snapshot/ReadPair.c
doc/3d-snapshot/ReadPairWrapper.c
doc/3d-snapshot/Smoker.c
doc/3d-snapshot/SmokerWrapper.c
doc/3d-snapshot/TaggedUnion.c
doc/3d-snapshot/TaggedUnionWrapper.c
doc/3d-snapshot/Triangle.c
doc/3d-snapshot/Triangle2.c
doc/3d-snapshot/Triangle2Wrapper.c
doc/3d-snapshot/TriangleWrapper.c
src/3d/Binding.fst
src/3d/Main.fst
src/3d/Target.fst
src/3d/ocaml/Batch.ml

This PR contains two fixes:
* Do not print C wrappers for 3d modules that do not have an entrypoint.
* We do not reset the field error code table across modules now. So, emitted code looks something like (where `Test` depends on `Point` and `TPoint`):
```
TestWrapper.c:
void TestEverParseError(char *x, char *y, char *z);
static char* TestStructNameOfErr(uint64_t err) {
switch (EverParseFieldIdOfResult(err)) {
case 1: return "Point._PVT";
case 2: return "Point._PVT";
case 3: return "Point._TWO_D_POINT";
case 4: return "Point._TWO_D_POINT";
case 5: return "TPoint._THREE_D_POINT";
case 6: return "Test._CIRCLE";
case 7: return "Test._T";
case 8: return "Test._T";
case 9: return "Test._T";
default: return "";
}
}
static char* TestFieldNameOfErr(uint64_t err) {
switch …
```

Some fixes related to C entry points

---

src/3d/Ast.fst
src/3d/Binding.fst
src/3d/Binding.fsti
src/3d/Deps.fst
src/3d/Deps.fsti
src/3d/Desugar.fst
src/3d/GenMakefile.fst
src/3d/InlineSingletonRecords.fst
src/3d/Main.fst
src/3d/Simplify.fst
src/3d/StaticAssertions.fst
src/3d/Target.fst
src/3d/Target.fsti
src/3d/Translate.fst
src/3d/TranslateForInterpreter.fst
src/3d/TypeSizes.fst
src/3d/ocaml/Batch.ml
src/3d/ocaml/lexer.mll
src/3d/ocaml/parser.mly
src/3d/tests/output_types/ExternVector.3d
src/3d/tests/output_types/ExternVectorDriver.c
src/3d/tests/output_types/ExternVector_ExternalTypedefs.h
src/3d/tests/output_types/Makefile

This PR adds support for extern types and and actions in 3d, see here for a testcase: https://github.com/project-everest/everparse/commit/f8d4a460f0b65272c7cde42a3e2f44c746fd15c8.
With extern types, a 3d specification may contain uninterpreted typedefs and function declarations that can be used in the parsing actions. The 3d toolchain translates uses of these typedefs and function declarations as is to the C code, where they are linked with their programmer specified C implementations. This enables following kind of examples, where the programmer may parse a variable length array of `Point` structs to a `vector`:
```
extern typedef struct _Vec Vec
extern void Push(mutable Vec *vec, UINT32 x, UINT32 y)
typedef struct _POINT (mutable Vec *vec) {
UINT32 x;
UINT32 y
{:on-success
Push (vec, x, …
```

Support for extern types and actions in 3d

---

src/3d/prelude/EverParse3d.Interpreter.fst
src/3d/prelude/buffer/EverParse3d.InputStream.Buffer.Aux.fst

Removing the uses of `__temp_no_proj`, cf. https://github.com/FStarLang/FStar/pull/2466.

Removing temo no proj option, cf. F* PR 2466

---

src/3d/Ast.fst
src/3d/BitFields.fst
src/3d/tests/Bitfields0.3d

Bit fields can now have non-failing actions and they are sequentially composed when validating the field containing all the bits.
These actions were previously being dropped

fix for bitfield action, which were previously being silently dropped

---

tests/lowparse/Makefile

Until we add support for proper reification of indexed effects.

Turn off indexed effects reification based tests, cf. F* 2641

---

doc/3d-snapshot/Color.h
doc/3d-snapshot/EnumConstraint.h
src/lowparse/LowParse.Spec.Tac.Sum.fst
src/lowparse/LowParse.TacLib.fst

When FStarLang/FStar#2730 is merged, `term_eq` will have some slight differences in behavior. In particular it will not ignore universes any more so I believe most calls here will fail. Since these calls are meant to check if a term is equal to some particular top-level name, replace them with `is_fvar`.
**Note**: this function does not currently exist in F* (it is added by that same PR), so this should only be merged after that.
I got a local everest green with the updated F* and the patched everparse (no changes needed to other projects).
------
LowParse: tactics: remove calls to term_eq, use is_fvar instead
`term_eq` received some fixes in F* (such as honoring universes) that cause some failures here. The old behavior is accessible via a (Tac) primitive `term_eq_old`. but these calls …

Fix for a change to term_eq in F*

---

.docker/build/config.json
doc/Makefile
src/3d/Makefile
src/3d/ocaml/Makefile
src/3d/ocaml/dune.tmpl
src/3d/prelude/Makefile
src/3d/prelude/buffer/Makefile
src/3d/prelude/extern/Makefile
src/3d/tests/Makefile
src/3d/tests/output_types/Makefile
src/3d/tests/output_types/modules_batch/Makefile
src/lowparse/Makefile
src/package/package.sh
tests/bitfields/Makefile.common
tests/lowparse/Makefile
tests/sample/Makefile.common
tests/sample0/Makefile.common
tests/sample_client/Makefile
tests/sample_low/Makefile.common
tests/unit/Makefile

This PR is a companion to FStarLang/FStar#2815
With F* being built with `dune`, its library is now organized differently: `fstar-lib`, `fstar-compiler-lib` and `fstar-tactics-lib` are now merged into `fstar.lib` located in `$FSTAR_HOME/lib/fstar/lib/fstar_lib.cmx*` instead of `$FSTAR_HOME/bin/*.cmx*` So this PR fixes the dune builds for qd.exe and 3d.exe accordingly. In this process, FStar_Getopt.ml need no longer be copied from the F* sources, since it is already implemented in fstar.lib
This PR also improves the handling of the `FSTAR_HOME` environment variable in Makefiles, so that EverParse can now be compiled and tested even if F* is installed from opam (or with `make install`), with `fstar.exe` in the `PATH`, so that the user need no longer set `FSTAR_HOME` in such cases.
I have an …

F*+dune: new F* library layout, improved handling of FSTAR_HOME

---

src/3d/prelude/extern/EverParse3d.InputStream.Extern.fst

Needed to merge https://github.com/FStarLang/FStar/pull/2835, which somehow breaks this proof. Thankfully it just seems like normal flakiness, so this can be merge before the F* PR. Note the use of `--split_queries`, it makes the proof more stable (otherwise it fails, retries the query to localize errors, and ends up succeeding with a warning).

EverParse3d.InputStream.Extern.fst: proof maintenance

---

src/3d/FStar.Getopt.fsti

This module will be removed from F*'s library.
See https://github.com/FStarLang/FStar/pull/2883

getopt: remove use of FStar.BaseTypes

---

src/3d/Target.fst
src/3d/prelude/EverParse3d.Prelude.fsti

The `range` type and `labeled` function were moved.

EverParse3d: Prelude: update for FStarLang/FStar#2892

---

src/lowparse/LowParse.Low.BoundedInt.fst
src/lowparse/LowParse.SLow.BoundedInt.fst

Hi Tahina, I needed to bump some rlimits to get an everest green for a change that's coming to F* (https://github.com/FStarLang/FStar/commit/fc1b447469df181057d6cf2c7d16926cc61cbfd4, https://github.com/FStarLang/FStar/issues/2894).
Would be good if, given that it comes back green, we merge this before to avoid breakage and syncing up.

lowparse: rlimit tweaks for new F*

---

.docker/build/config.json
src/3d/EverParseEndianness.h
src/3d/EverParseEndianness_Windows_NT.h

FStarLang/karamel#381 now generates `KRML_HOST_IGNORE(x)` in the body of a validator `v(x)` if `x` is an argument not used in that body.
Since EverParse uses `krml -minimal` and defines all Karamel constants and symbols in `EverParseEndianness.h`  and `EverParseEndianness_Windows_NT.h`, we need to define `KRML_HOST_IGNORE` there.
This issue should fix #80 .

Define KRML_HOST_IGNORE to mark unused arguments

---

src/3d/Binding.fst
src/3d/Desugar.fst
src/3d/tests/Bitfields0.3d
src/3d/tests/FAILArrayBitWidth.3d
src/3d/tests/FAILArrayRefinement.3d
src/3d/tests/Makefile

* Forbid refinements and bitwidths on non-scalar fields
* A bit field ends with the type of the underlying field changes. Previously 3D would reject this:
```
//bitfield boundaries coincide with the the types of their underlying fields
typedef struct _BFBoundary {
UINT16 x : 12; //4 bits of padding here are implicit
UINT8 y : 4;
UINT8 z : 3; //y and z are packed, but with 1 bit of padding left
UINT16 w : 12; //4 bits of padding here are implicit
} BFBoundary;
```
since the field `y` could be packed into the 16 bit field that contains `x`, but `y` has a different type than `x`. Now, it is accepted.
Thanks to @Smfakhoury for finding these issues.

Two bug fixes

---

doc/3d-snapshot/BF.c
doc/3d-snapshot/BoundedSumWhere.c
doc/3d-snapshot/EnumConstraint.c
doc/3d-snapshot/Smoker.c
src/3d/Main.fst
src/3d/OS.fsti
src/3d/Options.fst
src/3d/Options.fsti
src/3d/Target.fst
src/3d/Target.fsti
src/3d/TranslateForInterpreter.fst
src/3d/Z3TestGen.fst
src/3d/ocaml/OS.ml
src/3d/tests/TestSMT.3d

This PR introduces 3D option `--test_checker`, which, when followed by a parser name of the form `Modulename.parsername`, generates a test executable, `test.exe`, so that `./test.exe filename.dat arg1 arg2...` opens the file `filename.dat` and runs the validator for `Modulename.parsername`, with arguments `arg1`, `arg2`..., on the binary data contained in that file, and returns 0 if the data in the file passes validation, 1 if it fails validation, 2 for any other error (wrong number of arguments, file is missing, cannot mmap, etc.)
The file passed to `test.exe` is assumed to contain all of the input data to be passed to the validator, in binary form. If the user wants to start from some `filename.hex` that contains hex data instead (e.g. .pcap), it is the responsibility of the user to …

Generate test checker executable

---

src/3d/prelude/extern/EverParse3d.InputStream.Extern.fst

This proof regressed again. I tried to stabilize it by splittin queries, but ran into this:
```
(EverParse3d.InputStream.Extern.fst(246,1-271,5))	Query-stats (EverParse3d.InputStream.Extern.peep, 63)	failed {reason-unknown=unknown because Overflow encountered when expanding old_vector} in 42 milliseconds with fuel 0 and ifuel 1 and rlimit 256 
```
which is a z3 bug. To work around it I also added --z3refresh, and now this works reliably, albeit slowly.
I wanted to add hints but noticed there are none in the repo?

EverParse3d.InputStream.Extern.fst: fix proof regression

---

src/3d/tests/tcpip/VXLAN.3d

A VxLAN network identifier (VIN) is 24 bits/3 octets.
Found by assembling packets as part of 3DGen:
```bash
@lemmy ➜ /workspaces/RFC-3D (mku-tshark) $ ./validate_with_tshark.py 
Temporary directory created at: /tmp/tmptarwfqr8
Traceback (most recent call last):
File "/workspaces/RFC-3D/./validate_with_tshark.py", line 47, in <module>
vxlan = VXLAN(pkt_layer)
File "/home/codespace/.python/current/lib/python3.10/site-packages/scapy/base_classes.py", line 399, in __call__
i.__init__(*args, **kargs)
File "/home/codespace/.python/current/lib/python3.10/site-packages/scapy/packet.py", line 165, in __init__
self.dissect(_pkt)
File "/home/codespace/.python/current/lib/python3.10/site-packages/scapy/packet.py", line 1029, in dissect
s = self.do_dissect(s)
File …
```

VxLAN packets are two octets short.

---

.github/workflows/windows.yaml
src/package/windows/build-everparse.ps1
src/package/windows/build-everparse.sh
src/package/windows/everest.sh
src/package/windows/opam-packages

This PR enables an action workflow to produce a EverParse binary package for Windows and upload it as a build artifact.
Right now the corresponding workflow is enabled only for pull requests or on-demand, as opposed to Linux binary packages which are produced and uploaded at every push.

Produce and upload a Windows binary package

---

doc/3d-snapshot/BF.c
doc/3d-snapshot/BoundedSumWhere.c
doc/3d-snapshot/GetFieldPtr.c
doc/3d-snapshot/Triangle2.c
src/3d/ocaml/Batch.ml

This PR makes 3d call KaRaMeL with the `-fno-shadow` option to avoid local variable shadowing in the generated C code. Thanks @msprotz for your advice!

Avoid local variable shadowing in generated C code

---

src/3d/tests/tcpip/IPV4.3d

>   Total Length:  16 bits
Total Length is the length of the datagram, measured in octets,
including internet header and data.  This field allows the length of
a datagram to be up to 65,535 octets.  Such long datagrams are
impractical for most hosts and networks.  All hosts must be prepared
to accept datagrams of up to 576 octets (whether they arrive whole
or in fragments).  It is recommended that hosts only send datagrams
larger than 576 octets if they have assurance that the destination
is prepared to accept the larger datagrams.
The number 576 is selected to allow a reasonable sized data block to
be transmitted in addition to the required header information.  For
example, this size allows a data block of 512 octets plus 64 header
octets to fit in a datagram.  The maximal internet …

Total Length is the length of the datagram, measured in octets, *including* internet header and data.

---

src/3d/tests/tcpip/UDP.3d

https://www.ietf.org/rfc/rfc768.txt
> Length  is the length  in octets  of this user datagram  including  this header  and the data.   (This  means  the minimum value of the length is eight.)
https://en.wikipedia.org/wiki/User_Datagram_Protocol#UDP_datagram_structure
> This field specifies the length in bytes of the UDP header and UDP data. The minimum length is 8 bytes, the length of the header. The field size sets a theoretical limit of 65,535 bytes (8-byte header + 65,527 bytes of data) for a UDP datagram. However, the actual limit for the data length, which is imposed by the underlying [IPv4](https://en.wikipedia.org/wiki/IPv4) protocol, is 65,507 bytes (65,535 bytes − 8-byte UDP header − 20-byte [IP header](https://en.wikipedia.org/wiki/IPv4_header)).[[5]](https://en.wikipedia.org/wik …

Add constraint for UDP's length field

---

src/3d/InterpreterTarget.fst
src/3d/InterpreterTarget.fsti
src/3d/Target.fst
src/3d/Target.fsti
src/3d/TranslateForInterpreter.fst
src/3d/Z3TestGen.fst
src/3d/prelude/EverParse3d.Actions.Base.fst
src/3d/prelude/EverParse3d.Actions.Base.fsti
src/3d/prelude/EverParse3d.Interpreter.fst

Consider the following 3D data format description:
```
entrypoint typedef struct _test {
UINT16 x;
} test;
```
From this definition, currently, 3D generates F* code that does not typecheck, because entrypoints are not supposed to have a reader, and the way we currently enforce this requirement is to forbid such definitions.
This PR relaxes this requirement to allow those definitions, by casting entrypoint validators with `validate_drop` to weaken their types.

3d: weaken allow_reading for entrypoints

---

src/3d/GlobalEnv.fst
src/3d/Options.fst
src/3d/StaticAssertions.fst
src/3d/TypeSizes.fst
src/3d/TypeSizes.fsti
src/3d/Utils.fst
src/3d/tests/modules/src/Foobar.h

Adding offsetof checks as static assertions when refining a C type

---

src/3d/FStarC.Getopt.fsti
src/3d/Makefile
src/3d/Options.fst

Hi Tahina, this is needed after F* PR https://github.com/FStarLang/FStar/pull/3557

Moving FStar.Getopt -> FStarC.Getopt

---

src/ASN1/ASN1.Spec.Interpreter.fst

Running `make` in `everparse/src/ASN1` gets error:
```
* Error 19 at ASN1.Spec.Interpreter.fst(64,80-64,103):
- Could not prove termination of this recursive call
- The SMT solver could not prove the query. Use --query_stats for more
details.
- See also ASN1.Spec.Interpreter.fst(61,2-94,60)
* Error 19 at ASN1.Spec.Interpreter.fst(101,23-101,48):
- Could not prove termination of this recursive call
- The SMT solver could not prove the query. Use --query_stats for more
details.
- See also ASN1.Spec.Interpreter.fst(97,2-101,125)
```
Thank you for replying @nikswamy .

Update ASN1.Spec.Interpreter.fst with converters in ASN1.Base.fst

---

src/3d/Target.fst
src/3d/Target.fsti
src/3d/TranslateForInterpreter.fst

Similarly, I had to add a `T_nlist` node in `Target.typ`

also simplify compile-time constant-sized lists in pairs

---

src/3d/Getopt.fsti
src/3d/Options.fst
src/3d/ocaml/Getopt.ml

This is a follow up to #148.
Coding against internal modules of the F* compiler is not maintainable,
and there is no need to do so here. With the new build, fstar-lib will
not even include this module (although maybe it could eventually), so
this is also more future-proof.

Remove dependency on fstar's Getopt

---

src/3d/GenMakefile.fst
src/3d/OS.fsti
src/3d/ocaml/Batch.ml
src/3d/ocaml/OS.ml
src/3d/prelude/Makefile
src/3d/prelude/buffer/Makefile
src/3d/prelude/extern/Makefile
src/3d/tests/Makefile
src/3d/tests/iter/coarse/src/Test.3d
src/3d/tests/iter/coarse/src/Test_ExternalTypedefs.c
src/3d/tests/iter/coarse/src/Test_ExternalTypedefs.h
src/3d/tests/iter/coarse/src/main.c
src/3d/tests/iter/fine/src/Test.3d
src/3d/tests/iter/fine/src/Test_ExternalTypedefs.c
src/3d/tests/iter/fine/src/Test_ExternalTypedefs.h
src/3d/tests/iter/fine/src/main.c
src/3d/tests/output_types/ExternVectorDriver.c
src/3d/tests/output_types/ExternVector_ExternalTypedefs.h
src/3d/tests/output_types/Makefile
src/3d/tests/output_types/modules_batch/Makefile

This PR integrates some changes to build and test EverParse with the official opam 2.3 for Windows.
Among others:
* GenMakefile GMake now always uses `/` in rule prerequisites and targets, even on Windows.
* fixing 3d tests to avoid some type names used in Cygwin headers (`OUT`, `POINT`)

Some adjustments to run on Windows

---

doc/3d-snapshot/ProbeWrapper.c
doc/3d-snapshot/ProbeWrapper.h
doc/Probe.3d
src/3d/Binding.fst

* Probe length expressions can mention sizeof(this), where this resolves to the name of the enclosing type, or in the case of probe attributes, to the type on which the attribute appears
* I also fixed the documentation of probe to use sizeof(this), and corrected the last example which had a misplaced extra probe

Allow probe length expressions to mention sizeof(this)

---

.docker/produce-binary.Dockerfile
.github/workflows/windows.yaml
src/package/package.sh

This PR adapts Windows CI to the new [official Windows support for OCaml with opam 2.3](https://ocaml.org/docs/ocaml-on-windows).
For now this PR assumes a CI machine already configured with `windows-init.ps1` introduced by project-everest/everest#118. In other words, this PR **does not** adapt `src/package/windows/` to the new official opam 2.3; there is no unattended machine configuration yet.
However, this PR now tests the EverParse binary package on a GitHub-hosted runner, to make sure the package can work on a bare Windows machine without Cygwin, OCaml, etc.

Adapt Windows CI to new opam 2.3

---

src/3d/Ast.fst
src/3d/Binding.fst
src/3d/Desugar.fst
src/3d/TranslateForInterpreter.fst
src/3d/TypeSizes.fst
src/3d/ocaml/parser.mly
src/3d/tests/Align.3d
src/3d/tests/AlignC.h

An old, ugly, unused feature of 3D to auto-generate a name for a pointer to a struct causes unexpected shadowing.
In particular, say you have:
```
typedef struct _T {
UINT32 x;
} T;
```
Then, 3D would also implicit bind the name PT to the type T*, this name can shadow the use of a `PT` already defined, leading to much confusion.
This PR fixes it by no longer auto-generating such a name, which is much more sane.

Fix implicit shadowing by an auto-generated "pointer-name" for a struct

---

src/3d/tests/.gitignore
src/3d/tests/Makefile

Hi Tahina, this is a tiny patch to reduce the errors shown in action logs.
 
In the successful case, these tests output F* errors that will then show up in logs for CI runs (e.g.
https://github.com/mtzguido/FStar/actions/runs/13357223228). Redirect the output and error output to files so they do not show up, but can still be inspected manually.

3d tests: redirect output of negative tests

---

.github/workflows/ci.yml
.github/workflows/package-windows.yml
src/3d/Batch.fsti
src/3d/Main.fst
src/3d/OS.fsti
src/3d/Options.fst
src/3d/Options.fsti
src/3d/Z3TestGen.fst
src/3d/ocaml/Batch.ml
src/3d/ocaml/OS.ml
src/3d/ocaml/Z3.ml
src/3d/tests/.gitignore
src/3d/tests/ELF.3d
src/3d/tests/ELFTestGen.3d
src/3d/tests/Makefile
src/package/everparse.cmd
src/package/package.sh

* When doing test case generation on Windows, 3D now runs Z3 sequentially, since native Windows does not support `Unix.fork`
* With --z3_test and --z3_diff_test, the test case executable is now compiled and run also on Windows, thanks to FStarLang/karamel#535
Other improvements not related to Windows:
* In test case generation mode (--z3_test or _z3_diff_test), 3D now produces a C test case module by default, testcases.c, even with --no_batch. To avoid producing this test case module, 3D accepts the new option `--z3_skip_testcases_c`
* The test case executable now prints the test case definitions as C global variables with everything else commented out
* Use C11 `memset` instead of BSD/non-POSIX `bzero` to initialize outparameters
* Use `NULL` instead of zero-sized stack arrays
* …

3D test case generation on Windows

---

src/3d/Batch.fsti
src/3d/GenMakefile.fst
src/3d/GenMakefile.fsti
src/3d/Main.fst
src/3d/Options.fst
src/3d/Options.fsti
src/3d/ocaml/Batch.ml

So far with `--clang_format`, 3D copies the style configuration file from https://github.com/project-everest/everparse/blob/master/src/3d/.clang-format into the output directory specified by `--odir`.
This PR introduces `--clang_format_use_custom_config` to skip that copy. Instead, 3D will assume that a `.clang-format` file already exists in the output directory. In particular, the Makefile generated by `--makefile` will still add `.clang-format` to the prerequisites of `.c` and `.h` files, but will no longer generate a rule to produce/copy it.

3d: use custom `.clang-format` assumed to exist in output directory

---

doc/Makefile

This reverts commit 343d76f80e81da1cc615ce7ebb56aa401f991c96.
Regenerating html is part of CI, not tests

Revert "regenerate html as part of tests (but do not upload them)"

---

.github/workflows/cbor.yml
.github/workflows/ci.yml
.github/workflows/nightly.yml
Makefile
opt/.gitignore
opt/Makefile
opt/env.Makefile
src/cbor/pulse/det/rust/src/cbordetveraux.rs
src/cbor/pulse/det/rust/target/doc/src/cborrs/cbordetveraux.rs.html
src/cose/Makefile
src/cose/rust/src/cbordetveraux.rs
src/cose/verifiedinterop/.gitignore
src/cose/verifiedinterop/test/Makefile

This PR removes HACL* from ` opt/`, since it is not needed to build EverCOSE. Rather, this PR makes HACL* local to the COSE verified interop test: just like qcbor and tinycbor, HACL* is now downloaded by that test, and only then; and it is skipped if `HACL_HOME` is set.

Remove HACL* from opt/

---

src/cbor/pulse/raw/CBOR.Pulse.Raw.Insert.fst

Can we do something about this proof? 128 is already on the high side. This just failed in everest.
Not sure if 192 is enough.

Bump rlimit

---

.github/workflows/cbor.yml
.github/workflows/ci.yml
.github/workflows/nightly.yml
.gitignore
Dockerfile
Makefile
build-evercddl.sh
git.Dockerfile
opt/.gitignore
opt/Makefile
opt/env.Makefile
opt/git-clone.Makefile
opt/opam-env.sh
opt/shell.sh
src/cose/verifiedinterop/test/Makefile

Currently, the user needs to run `make _opam && eval $(opam env) && make -C opt` to build EverParse dependencies. Moreover, `make _opam` touches the user's `.opam` by registering a switch.
This PR fixes all of those issues. Now, the user only needs to run `make -C opt` to build all EverParse dependencies at once, including opam packages. To perform the latter, `make -C opt` now creates a standalone opam root in `opt/opam`.
Moreover, `make -C opt` now creates `opt/opam-env.Makefile`, which is automatically included by the main `Makefile` to set up the opam environment in addition to `FSTAR_EXE`, etc. when invoking one of its rules. Thus, the user no longer needs to run `eval $(opam env)`.
As before, if the user needs to work beyond the main Makefile rules, a single invocation of `eval …

Use a standalone opam root, fuse opam package build into `make -C opt`

---

.github/workflows/cbor.yml
Makefile
deps.Makefile
src/cbor/pulse/det/c/example/Makefile
tests/bitfields/Makefile.common
tests/sample/Makefile.common
tests/sample0/Makefile.common
tests/sample_low/Makefile.common
tests/unit.Makefile

Remaining things disabled on MacOS:
* `cose`, `cose-test`: disabled because we don't know how to link with OpenSSL
* `3d-unit-test`: disabled because there seems to be a loop in Makefiles
* `3d-doc-test`: disabled because sphinx is not available

CI: test as much as possible on MacOS
